// source/react/Queta.tsx
import type * as Glaemscribe from 'glaemscribe'
import React, { Component } from 'react'
import type {
	ITranslator,
	resolve as resolveFn,
	translate as translateFn,
} from '../translate/translate'

type TProps = {
	className?: string,
	language?: string,
	typeface?: string,
	writing?: Glaemscribe.Writing,
}

type TState = {
	loading: boolean,
	resolve?: typeof resolveFn,
	translate?: typeof translateFn,
}

export class Queta extends Component<TProps, TState> {
	private static dependencies = import('~/translate/translate')
		.then(module => module.dependencies.then(() => ({
			resolve: module.resolve,
			translate: module.translate,
		})))

	#loading = Queta.dependencies.then(({ resolve, translate }) => {
		this.setState({ loading: false, resolve, translate })
	})

	public static defaultProps: TProps = {
		language: 'quenya-tengwar-classical',
		typeface: 'tengwar_guni_sindarin',
		writing: 'Tengwar',
	}
	public state: TState = {
		loading: true,
	}

	#renderChildren = (children: React.ReactNode): React.ReactChild[] => (
		(React.Children.toArray(children) as React.ReactChild[]).map((child, index) => {
			if (typeof child === 'string') {
				const { language, typeface } = this.props
				const { success, translation } = this.state.translate(child, language, typeface)
				if (success) { return translation }
			} else if (typeof child === 'number') {
				return child
			} else if (child?.props?.children) {
				const grandChildren = child.props.children
				const Type = child.type
				return (
					<Type key={index} {...child.props}>
						{this.#renderChildren(
							Array.isArray(grandChildren)
								? grandChildren
								: [grandChildren],
						)}
					</Type>
				)
			}

			return child
		})
	)

	render = (): JSX.Element => {
		const { children, className, language, typeface } = this.props
		const { loading, resolve } = this.state
		const { charset, mode } = loading ? {} as ITranslator : resolve(language, typeface)

		const classes = [
			'glaemscribe',
			className,
			mode?.name,
			charset?.name,
			loading && 'loading',
		].filter(Boolean).join(' ')

		return (
			<div className={classes}>
				{!loading && this.#renderChildren(children)}
			</div>
		)
	}
}

// source/web-components/queta.ts
import type {
	resolve as resolveFn,
	translate as translateFn,
} from '../translate/translate'

class Component extends HTMLElement {
	private static dependencies = import('~/translate/translate')
		.then(module => module.dependencies.then(() => ({
			resolve: module.resolve,
			translate: module.translate,
		})))

	defaultLanguage: string = 'quenya-tengwar-classical'
	defaultTypeface: string = 'tengwar_guni_sindarin'

	#loading: boolean
	#resolve: typeof resolveFn
	#translate: typeof translateFn

	#slot: HTMLSlotElement
	#span: HTMLSpanElement

	constructor() {
		super()
		const shadowRoot = this.attachShadow({ mode: 'closed' })
		this.#slot = Object.assign(document.createElement('slot'), { style: 'display: none;' })
		this.#span = document.createElement('span')
		shadowRoot.append(this.#slot, this.#span)

		Component.dependencies.then(({ resolve, translate }) => {
			this.#loading = false
			this.#resolve = resolve
			this.#translate = translate

			shadowRoot.appendChild(
				document.querySelector('link#queta-styles').cloneNode(),
			)
		})

		this.#loading = true
		this.#render()
		Component.dependencies.then(() => {
			this.#loading = false
			this.#render()
		})
	}

	attributeChangedCallback(name, oldValue, newValue) {
		this.#render()
	}

	#renderChildren = (
		source: Element,
		target: Element,
		language?: string,
		typeface?: string,
	): void => {
		Array.from(source.childNodes).forEach(child => {
			if (child instanceof Text) {
				const { success, translation } = this.#translate(child.data, language, typeface)
				target.appendChild(new Text(success ? translation : child.data))
			}
			// } else if (typeof child === 'number') {
			// 	return child
			// } else if (child?.props?.children) {
			// 	const grandChildren = child.props.children
			// 	const Type = child.type
			// return (
			// 	<Type key={index} {...child.props}>
			// 		{this.#renderChildren(
			// 			Array.isArray(grandChildren)
			// 				? grandChildren
			// 				: [grandChildren],
			// 		)}
			// 	</Type>
			// )
			// }
		})
	}

	#render = (): void => {
		const className = this.getAttribute('class') ?? ''

		if (this.#loading) {
			this.#span.innerHTML = ''
			this.#span.className = 'queta loading'
			return
		}

		const { charset, mode } = this.#resolve(
			this.getAttribute('lang') ?? this.defaultLanguage,
			this.getAttribute('typeface') ?? this.defaultTypeface,
		)
		const language = mode?.name
		const typeface = charset?.name

		this.#span.innerHTML = ''
		this.#span.className = ['queta', className, language, typeface].filter(Boolean).join(' ')
		this.#renderChildren(this, this.#span, language, typeface)
	}
}

window.customElements.define('queta-text', Component)
